name: Deploy Javadoc

on:
  push:
    branches:
      - master
jobs:
  publish:
    environment: dep # æ³¨æ„ç¯å¢ƒ
    runs-on: ubuntu-latest
    steps:
      - name: Deploy JavaDoc ğŸš€
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.SECRET_KEY }}
          javadoc-branch: api_doc
          java-version: 8
          target-folder: /
          without-deploy: true